// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'content': string;
  'directory-menu': string;
  'homepage': string;
  'menu-item': string;
  'subtitle': string;
  'title': string;
}
declare const cssExports: CssExports;
export = cssExports;
